##Weather Observation Station
##1.
SELECT city, state FROM STATION;

##2.
SELECT ROUND(SUM(LAT_N),2), ROUND(SUM(LONG_W),2) FROM STATION;

##3.
SELECT DISTINCT city FROM STATION
WHERE ID%2 = 0;

##4.
SELECT COUNT(CITY)-COUNT(DISTINCT CITY) FROM STATION;

##5.
SELECT * FROM (SELECT CITY, LENGTH(CITY) AS len FROM STATION ORDER BY len, CITY) length
LIMIT 1;
SELECT * FROM (SELECT CITY, LENGTH(CITY) AS len FROM STATION ORDER BY len DESC, CITY) length
LIMIT 1;